"""Added cables

Revision ID: 0f0c28a1aec0
Revises: ea1aa304183f
Create Date: 2022-11-12 22:25:42.455413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0c28a1aec0'
down_revision = 'ea1aa304183f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cable_type_id', sa.Integer(), nullable=False),
    sa.Column('start_outlet_id', sa.Integer(), nullable=False),
    sa.Column('end_outlet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cable_type_id'], ['cable_types.id'], name=op.f('fk_cables_cable_type_id_cable_types')),
    sa.ForeignKeyConstraint(['end_outlet_id'], ['outlets.id'], name=op.f('fk_cables_end_outlet_id_outlets')),
    sa.ForeignKeyConstraint(['start_outlet_id'], ['outlets.id'], name=op.f('fk_cables_start_outlet_id_outlets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cables'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cables')
    # ### end Alembic commands ###
