"""initial db models

Revision ID: ac2d3a256c23
Revises: 
Create Date: 2022-10-31 11:15:21.213638

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ac2d3a256c23"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.UnicodeText(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_areas")),
        sa.UniqueConstraint("short_name", name=op.f("uq_areas_short_name")),
    )
    op.create_table(
        "cable_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.UnicodeText(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cable_types")),
    )
    op.create_table(
        "cable_types_wires",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("second_color", sa.String(length=7), nullable=True),
        sa.Column("cable_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cable_type_id"],
            ["cable_types.id"],
            name=op.f("fk_cable_types_wires_cable_type_id_cable_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cable_types_wires")),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.UnicodeText(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"], ["areas.id"], name=op.f("fk_places_area_id_areas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
        sa.UniqueConstraint("short_name", name=op.f("uq_places_short_name")),
    )
    op.create_table(
        "faces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("description", sa.UnicodeText(), nullable=True),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"], ["places.id"], name=op.f("fk_faces_place_id_places")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faces")),
        sa.UniqueConstraint(
            "place_id", "order_index", name=op.f("uq_faces_place_id_order_index")
        ),
        sa.UniqueConstraint("short_name", name=op.f("uq_faces_short_name")),
    )
    op.create_table(
        "outlets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.UnicodeText(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "SINGLE",
                "DOUBLE",
                "TRIPLE",
                "QUADRUPLE",
                "PLAIN",
                "DISTRIBUTOR",
                "OTHER",
                name="outletkind",
            ),
            nullable=False,
        ),
        sa.Column("face_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["face_id"], ["faces.id"], name=op.f("fk_outlets_face_id_faces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outlets")),
        sa.UniqueConstraint("short_name", name=op.f("uq_outlets_short_name")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outlets")
    op.drop_table("faces")
    op.drop_table("places")
    op.drop_table("cable_types_wires")
    op.drop_table("cable_types")
    op.drop_table("areas")
    # ### end Alembic commands ###
