"""added cable kind

Revision ID: ea1aa304183f
Revises: ac2d3a256c23
Create Date: 2022-10-31 12:12:25.132867

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from wire_service.service_model.cable_kind import CableKind

# revision identifiers, used by Alembic.
revision = "ea1aa304183f"
down_revision = "ac2d3a256c23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    cable_kind = postgresql.ENUM(CableKind, name="cablekind")
    cable_kind.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "cable_types",
        sa.Column("kind", cable_kind, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cable_types", "kind")
    # ### end Alembic commands ###
